sonar.projectKey=ddelbarriojuan-code_Proyecto_web
sonar.organization=ddelbarriojuan-code
sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
